[project]
name = "agent-reasoning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-generativeai>=0.8.4",
    "ipykernel>=6.29.5",
    "ollama>=0.4.6",
    "openai>=1.59.9",
    "python-dotenv>=1.0.1",
]
